//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int cart_id { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Cart Cart1 { get; set; }
    }
}
